# Configuration for Minetrix

homeserver:
  domain: "example.com"

# Username and password to access the specified homeserver
username: "@minetrix:example.com"
password: "changeme"

# The room ID forward send messages from/to
room_id: "!foo:example.com"

# Adds a tooltip to the sender
sender_tooltips: false